version: 2.1
commands:
    node-install:
        steps:
            - run: npm ci
    npm-deploy:
        steps:
            - run: echo "registry=https://registry.npmjs.org" >> .npmrc
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
            - run: npm version $CIRCLE_TAG --allow-same-version --no-git-tag-version
            - run: npm publish --access public
jobs:
    install-build-deploy:
        docker:
            - image: node:12
        steps:
            - checkout
            - node-install
            - npm-deploy
workflows:
    install-build-deploy:
        jobs:
            - install-build-deploy:
                context:
                    - npm-org-token
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
